### PR TITLE
Add extra variables

### PR DESCRIPTION
**Pull request by AaronDavidSchneider**
Hi @cspencerjones,

I tried to address the changes requested in https://github.com/MITgcm/xmitgcm/pull/205 by adding a test and extending the docstring.

Cheers
Aaron

### CODE REVIEW

**Comment by AaronDavidSchneider** [comment]
Hi @cspencerjones,
if you do not have the time to continue on this PR, I would be happy to create a new PR at xmitgcm.
Cheers

**Comment by cspencerjones** [comment]
Sorry - totally slipped my mind! All the builds are failing though. Can you have a look at that? I will try to pay more attention this week.

**Comment by cspencerjones** [comment]
And thanks for working on this @AaronDavidSchneider ...I remember it being a pretty difficult thing to do!

**Comment by AaronDavidSchneider** [comment]
Hi @cspencerjones,
thanks for your message. The problem was that there are some incomplete test datasets. Should be fixed now (hopefully)

**Comment by AaronDavidSchneider** [comment]
The errors are not related to this function as far as I can see

**Comment by cspencerjones** [comment]
I agree and I'm a bit lost about where these are from - I'll merge and we can try to figure it out in the main PR.

**Comment by AaronDavidSchneider** [comment]
Thanks!

**Pull request merged**
